export const predefinedCategories: { value: string; label: string }[] = [
  { value: 'Web Development', label: 'Web Development' },
  { value: 'Mobile Development', label: 'Mobile Development' },
  { value: 'Graphic Design', label: 'Graphic Design' },
  { value: 'Logo Design', label: 'Logo Design' },
  { value: 'UI/UX Design', label: 'UI/UX Design' },
  { value: 'SEO', label: 'SEO' },
  { value: 'Content Writing', label: 'Content Writing' },
  { value: 'Copywriting', label: 'Copywriting' },
  { value: 'Social Media Marketing', label: 'Social Media Marketing' },
  { value: 'Marketing Strategy', label: 'Marketing Strategy' },
  { value: 'Video Editing', label: 'Video Editing' },
  { value: 'Animation', label: 'Animation' },
  { value: 'Illustration', label: 'Illustration' },
  { value: 'Data Entry', label: 'Data Entry' },
  { value: 'Virtual Assistant', label: 'Virtual Assistant' },
  { value: 'Blockchain Development', label: 'Blockchain Development' },
  { value: 'AI & Machine Learning', label: 'AI & Machine Learning' },
  { value: 'Game Development', label: 'Game Development' },
  { value: 'E-commerce Development', label: 'E-commerce Development' },
  { value: 'Cybersecurity', label: 'Cybersecurity' },
  { value: 'Network Administration', label: 'Network Administration' },
  { value: 'Database Management', label: 'Database Management' },
  { value: 'Cloud Computing', label: 'Cloud Computing' },
  { value: 'DevOps', label: 'DevOps' },
  { value: 'Testing & QA', label: 'Testing & QA' },
  { value: 'Project Management', label: 'Project Management' },
  { value: 'Business Analysis', label: 'Business Analysis' },
  { value: 'Finance & Accounting', label: 'Finance & Accounting' },
  { value: 'Legal Consulting', label: 'Legal Consulting' },
  { value: 'Translation', label: 'Translation' },
  { value: 'Photography', label: 'Photography' },
  { value: 'Voice Over', label: 'Voice Over' },
  { value: 'Audio Production', label: 'Audio Production' },
  { value: 'Music Composition', label: 'Music Composition' },
  { value: '3D Modeling', label: '3D Modeling' },
  { value: 'Architecture', label: 'Architecture' },
  { value: 'Interior Design', label: 'Interior Design' },
  { value: 'Fashion Design', label: 'Fashion Design' },
  { value: 'Personal Styling', label: 'Personal Styling' },
  { value: 'Health & Fitness', label: 'Health & Fitness' },
  { value: 'Nutrition', label: 'Nutrition' },
  { value: 'Life Coaching', label: 'Life Coaching' },
  { value: 'Career Coaching', label: 'Career Coaching' },
  { value: 'Education & Tutoring', label: 'Education & Tutoring' },
  { value: 'Science & Research', label: 'Science & Research' },
  { value: 'Art & Crafts', label: 'Art & Crafts' },
  { value: 'Event Planning', label: 'Event Planning' },
  { value: 'HR Consulting', label: 'HR Consulting' },
  { value: 'Customer Support', label: 'Customer Support' },
  { value: 'Other', label: 'Other' },
];